### PR TITLE
Upgrade to Elm 0.19

### PR DESCRIPTION
**Pull request by klazuka**
Note that the tests have not yet been upgraded because `elm-test` is not ready for 0.19 yet.

### CODE REVIEW

**Comment by myrho** [comment]
Thx!

**Comment by klazuka** [comment]
@myrho I see that this was merged, but I don't actually see it in the master branch. In any case, just curious about when you intend to do a 0.19 release or if you would like me to create a new PR now that 0.19 is final (and elm-test is out)?

**Comment by myrho** [comment]
Yes ... I did some code refactoring on the 0.18 base due to #6. So I had to revert master, sorry.
Anyways, it's merged into master now but not published to. Can you run elm-test on it? I don't make it. Seems elm-test is not upgraded for 0.19 yet?

**Comment by klazuka** [comment]
@myrho the docs for using elm-test with 0.19 are not very good yet, but here's what you need to do:
1. `npm install -g elm-test@beta`
2. in your `elm.json` file's `test-dependencies` section, add the line `"elm-explorations/test": "1.0.0 <= v < 2.0.0"`
3. then run `elm-test`

I tried this on your project, but the tests fail to compile because Elm 0.19 removed support for tuples with more than 3 elements. Since all of your tests rely on a big tuple, modifying it is probably too risky for me, so I would leave it to you since you know the code better.

**Comment by myrho** [comment]
Ok, I updated the code and installed `elm-test@beta`. However, I still I don't get `elm-test` to run. Do you have a clue?

**Comment by klazuka** [comment]
What error are you seeing?

**Comment by myrho** [comment]
```
$ pwd
/home/matthias/workspace/elm-round
$ elm-test
-- BAD JSON ----------------------------------------------------------- elm.json

The "source-directories" in your elm.json lists the following directory:

    /home/matthias/workspace/www/elm-round/tests/src

I cannot find that directory though! Is it missing? Is there a typo?
```
Yes, of course this is not correct in `tests/elm.json`:

```
    "source-directories": [
        "src"
    ],
```
But if I change `src` to `.` which should be correct, I get almost the same error which makes no sense to me:

```
$ elm-test
-- BAD JSON ----------------------------------------------------------- elm.json

The "source-directories" in your elm.json lists the following directory:

    /home/matthias/workspace/www/elm-round/tests/tests

I cannot find that directory though! Is it missing? Is there a typo?
```

**Comment by klazuka** [comment]
one big change in 0.19 is that you no longer need a separate `elm-package.json` (now called `elm.json`) for your tests directory. So you should delete `tests/elm.json`. See if that fixes it. If you still have trouble, maybe try the `#testing` channel in Elm Slack.

**Comment by myrho** [comment]
Ok, then I got the following error message:

```
Received invalid JSON from test interface search: SyntaxError: Unexpected token  in JSON at position 0
```
So I removed `elm-stuff` and an unused `node_modules`. And also I copied `elm.json` from another Elm package where testing works, and adapted it again for my package.

Now `elm-test` works! Going to publish the package now.

**Comment by klazuka** [comment]
Cool. Thanks!

**Pull request merged**
